# NASA Query System Configuration

# LLM Configuration
llm:
  default_provider: "openai"
  providers:
    openai:
      api_key: "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"
      model: "gpt-4"
      temperature: 0.1
      max_tokens: 2000
    anthropic:
      api_key: "${ANTHROPIC_API_KEY}"
      model: "claude-3-sonnet-20240229"
      temperature: 0.1
      max_tokens: 2000
    local:
      model: "llama2-7b"
      temperature: 0.1
      max_tokens: 2000

# Query Router Configuration
router:
  kb_threshold: 0.7
  kg_threshold: 0.6
  rag_threshold: 0.4
  confidence_threshold: 0.8
  max_retries: 3

# Knowledge Base Configuration
kb:
  storage_path: "data/kb"
  index_type: "faiss"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  similarity_threshold: 0.8
  max_results: 10

# Knowledge Graph Configuration
kg:
  database_url: "bolt://localhost:7687"
  username: "neo4j"
  password: "password"
  max_depth: 3
  max_paths: 5
  relationship_types:
    - "STUDIED"
    - "USED_TECHNOLOGY"
    - "INVOLVED_RESEARCHER"
    - "LAUNCHED_FROM"
    - "RETURNED_TO"

# RAG Configuration
rag:
  vector_store_path: "data/rag"
  chunk_size: 1000
  chunk_overlap: 200
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  retrieval_k: 5
  rerank_top_k: 3

# Ingestion Pipeline
ingestion:
  supported_formats:
    - "pdf"
    - "json"
    - "md"
    - "txt"
    - "docx"
  batch_size: 10
  max_workers: 4
  processing_timeout: 300
  auto_index: true

# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  output_file: "logs/nasa_query.log"
  max_file_size: "10MB"
  backup_count: 5

# Debug Configuration
debug:
  enabled: false
  trace_queries: true
  show_routing_decisions: true
  visualize_graph: true
  save_intermediate_results: false

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  cors_origins: ["*"]
  rate_limit: 100
  timeout: 30

# Data Sources
data_sources:
  nasa_api:
    base_url: "https://data.nasa.gov"
    timeout: 30
    retry_attempts: 3
  local_data:
    path: "data/documents"
    auto_refresh: true
    refresh_interval: 3600 