# NASA Query System Configuration

# LLM Configuration
llm:
  default_provider: "openai"
  openai:
    model: "gpt-4"
    temperature: 0.1
    max_tokens: 2000
    api_key: "${OPENAI_API_KEY}"  # Use environment variable
  anthropic:
    model: "claude-3-sonnet-20240229"
    temperature: 0.1
    max_tokens: 2000
    api_key: "${ANTHROPIC_API_KEY}"  # Use environment variable

# Query Router Configuration
router:
  kb_threshold: 0.7
  kg_threshold: 0.6
  rag_threshold: 0.4
  confidence_threshold: 0.8
  max_retries: 3

# Knowledge Base Configuration
kb:
  storage_path: "data/kb"
  index_type: "faiss"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  similarity_threshold: 0.8
  max_results: 10

# Knowledge Graph Configuration
kg:
  database_url: "neo4j+s://72bbcca1.databases.neo4j.io"
  username: "neo4j"
  password: "TqEewyu6IUiWVzoaUXfHTjXAC2JHUg72C_p4AEIwJEY"
  max_depth: 3
  max_paths: 5
  relationship_types:
    - "STUDIED"
    - "USED_TECHNOLOGY"
    - "INVOLVED_RESEARCHER"
    - "LAUNCHED_FROM"
    - "RETURNED_TO"

# RAG Configuration
rag:
  # Pinecone Configuration
  pinecone_index_name: "nasa-docs"
  pinecone_api_key: "${PINECONE_API_KEY}"  # Use environment variable
  
  # Document Processing
  chunk_size: 500
  chunk_overlap: 50
  retrieval_k: 5
  rerank_top_k: 3

# Ingestion Pipeline
ingestion:
  supported_formats:
    - "pdf"
    - "json"
    - "md"
    - "txt"
    - "docx"
  batch_size: 10
  max_workers: 4
  processing_timeout: 300
  auto_index: true
  use_llm_extraction: true  # Enable LLM-based graph extraction

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/nasa_query_system.log"
  max_file_size: "10MB"
  backup_count: 5

# Debug Configuration
debug:
  enabled: false
  trace_queries: true
  show_routing_decisions: true
  visualize_graph: true
  save_intermediate_results: false
  show_routing_reasoning: true
  show_extraction_details: true

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  cors_origins: ["*"]
  rate_limit: 100
  timeout: 30

# Data Sources
data_sources:
  nasa_api:
    base_url: "https://data.nasa.gov"
    timeout: 30
    retry_attempts: 3
  local_data:
    path: "data/documents"
    auto_refresh: true
    refresh_interval: 3600 